### ISSUE TITLE
mnist example files are missing

### ISSUE THREAD

**Issue by dowobeha** [emjotde/Marian#13]
`$ ./mnist_benchmark 
Loading train set...terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open file `../examples/mnist/train-images-idx3-ubyte`!
Aborted (core dumped)`

Either these files should be included, or there should be documentation &/or a script to get them.

**Comment by hieuhoang** [comment]
Make

**Comment by dowobeha** [comment]
@hieuhoang: Umm, could you please elaborate?

**Comment by snukky** [comment]
Run `make` from `examples/mnist`. I think that in the future all examples (e.g. the MNIST example, a toy example, etc.) should be built optionally after enabling some CMake switch.
