### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by dowobeha** [emjotde/Marian#15]
[ 27%] Building NVCC (Device) object src/CMakeFiles/marian_lib.dir/marian_lib_generated_tensor.cu.o
/home/lanes/Marian/src/node_operators_unary.h(137): error: __host__ or __device__ annotation on lambda requires --expt-extended-lambda nvcc flag

/home/lanes/Marian/src/node_operators_unary.h(137): error: __host__ or __device__ annotation on lambda requires --expt-extended-lambda nvcc flag

/home/lanes/Marian/src/tensor_operators.h(88): error: The closure type for a lambda ("lambda [](float &, float)->float") cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is a 'extended lambda' and the flag --expt-extended-lambda is specified
          detected during:
            instantiation of "marian::gElement" based on template arguments <lambda [](float &, float)->float, marian::Tensor::TensorView, marian::Bernoulli> 
(88): here
            instantiation of "void marian::Element(Functor, T1, T2) [with Functor=lambda [](float &, float)->float, T1=marian::Tensor, T2=marian::Bernoulli]" 
/home/lanes/Marian/src/node_operators_unary.h(140): here

/home/lanes/Marian/src/tensor_operators.h(88): error: A type defined inside a __host__ function  ("lambda [](float &, float)->float") cannot be used in the template argument type of a __global__ function template instantiation
          detected during:
            instantiation of "marian::gElement" based on template arguments <lambda [](float &, float)->float, marian::Tensor::TensorView, marian::Bernoulli> 
(88): here
            instantiation of "void marian::Element(Functor, T1, T2) [with Functor=lambda [](float &, float)->float, T1=marian::Tensor, T2=marian::Bernoulli]" 
/home/lanes/Marian/src/node_operators_unary.h(140): here

/home/lanes/Marian/src/tensor_operators.h(88): error: The closure type for a lambda ("lambda [](float &, float)->float") cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is a 'extended lambda' and the flag --expt-extended-lambda is specified
          detected during:
            instantiation of "marian::gElement" based on template arguments <lambda [](float &, float)->float, marian::Tensor::TensorView, marian::Bernoulli> 
(88): here
            instantiation of "void marian::Element(Functor, T1, T2) [with Functor=lambda [](float &, float)->float, T1=marian::Tensor, T2=marian::Bernoulli]" 
/home/lanes/Marian/src/node_operators_unary.h(140): here

/home/lanes/Marian/src/tensor_operators.h(88): error: A type defined inside a __host__ function  ("lambda [](float &, float)->float") cannot be used in the template argument type of a __global__ function template instantiation
          detected during:
            instantiation of "marian::gElement" based on template arguments <lambda [](float &, float)->float, marian::Tensor::TensorView, marian::Bernoulli> 
(88): here
            instantiation of "void marian::Element(Functor, T1, T2) [with Functor=lambda [](float &, float)->float, T1=marian::Tensor, T2=marian::Bernoulli]" 
/home/lanes/Marian/src/node_operators_unary.h(140): here

3 errors detected in the compilation of "/tmp/tmpxft_00006419_00000000-7_expression_operators.cpp1.ii".
CMake Error at marian_lib_generated_expression_operators.cu.o.cmake:266 (message):
  Error generating file
  /home/lanes/Marian/build/src/CMakeFiles/marian_lib.dir//./marian_lib_generated_expression_operators.cu.o

make[2]: *** [src/CMakeFiles/marian_lib.dir/marian_lib_generated_expression_operators.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
3 errors detected in the compilation of "/tmp/tmpxft_00006422_00000000-7_expression_graph.cpp1.ii".
CMake Error at marian_lib_generated_expression_graph.cu.o.cmake:266 (message):
  Error generating file
  /home/lanes/Marian/build/src/CMakeFiles/marian_lib.dir//./marian_lib_generated_expression_graph.cu.o

make[2]: *** [src/CMakeFiles/marian_lib.dir/marian_lib_generated_expression_graph.cu.o] Error 1
make[1]: *** [src/CMakeFiles/marian_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by emjotde** [comment]
Works with a second make, though. Weird.
