### ISSUE TITLE
softmax appears to be broken in xor

### ISSUE THREAD

**Issue by dowobeha** [emjotde/Marian#21]
"result":	shape=4x1
0.995334 
0.00920105 
0.995334 
0.000189304 

"softmax":	shape=4x1
1 
1 
1 
1

**Comment by emjotde** [comment]
That's actually correct. You are trying to apply softmax as a decision function, which it is not. When applied to a single value, the value of softmax is always 1.

**Comment by dowobeha** [comment]
Ah, OK. I was just following usage in feedforward.h

**Comment by emjotde** [comment]
Sure, but this is not a multi-class problem, so softmax does not make much sense. Here you just want to apply a decision function like `output < 0.5` to the output.
